import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: 'Blogs',
    template: '%s | Blogs',
  },
  description: "Generated by create next app",
};
export default function BlogLayout({children}: LayoutProps<"/blogs">) {
  return (
    <>
      <h1 className="text-center text-4xl font-bold">Blogs Section</h1>
      {children}
    </>
  );
}
