import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body>
        <div className="flex flex-col h-screen justify-between bg-amber-200">
          <header className="bg-red-500 text-center h-8">Header</header>
          <div className="h-10">
            {children}
          </div>
          <footer className="bg-blue-400 text-center h-8">Footer</footer>
        </div>
      </body>
    </html>
  );
}
