import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: 'Parth',
    template: '%s | Parth',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body>
        <div className="flex flex-col h-screen justify-between">
          <header className="bg-red-500 text-center h-8">Header</header>
          <div className="flex-1 flex flex-col">
            {children}
          </div>
          <footer className="bg-blue-400 text-center h-8">Footer</footer>
        </div>
      </body>
    </html>
  );
}
